# Generated by Django 2.1.7 on 2019-07-01 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='duration',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 9, 50, 25, 79604)),
        ),
        migrations.AlterField(
            model_name='seller',
            name='store_logo',
            field=models.ImageField(default='nologo.jpg', max_length=200, null=True, upload_to='store_logo'),
        ),
    ]
